import type { NorseOneRole } from "@/types/norse-one";

export type NorseOnePermission =
  // Identity
  | "VIEW_OWN_PROFILE"
  | "VIEW_CHILD_PROFILE"
  | "VIEW_STUDENTS"

  // Curriculum
  | "VIEW_CURRICULUM"
  | "SEARCH_CURRICULUM"
  | "CREATE_CURRICULUM"
  | "EDIT_CURRICULUM"
  | "PUBLISH_CURRICULUM"
  | "ARCHIVE_CURRICULUM"
  | "RESTORE_CURRICULUM"
  | "VIEW_CURRICULUM_HISTORY"

  // Attendance
  | "VIEW_OWN_ATTENDANCE"
  | "VIEW_CHILD_ATTENDANCE"
  | "VIEW_CLASSROOM_ATTENDANCE"
  | "SEARCH_ATTENDANCE"
  | "CREATE_ATTENDANCE"
  | "EDIT_ATTENDANCE"
  | "CORRECT_ATTENDANCE"
  | "VIEW_ATTENDANCE_HISTORY"

  // Messages
  | "VIEW_OWN_MESSAGES"
  | "VIEW_CHILD_MESSAGES"
  | "VIEW_STAFF_MESSAGES"
  | "SEARCH_MESSAGES"
  | "SEND_MESSAGE"
  | "EDIT_MESSAGE"
  | "ARCHIVE_MESSAGE"
  | "VIEW_MESSAGE_HISTORY"

  // Admissions
  | "VIEW_OWN_ADMISSION"
  | "VIEW_FAMILY_ADMISSION"
  | "SEARCH_ADMISSIONS"
  | "CREATE_ADMISSION"
  | "EDIT_ADMISSION"
  | "REVIEW_ADMISSION"
  | "APPROVE_ADMISSION"
  | "DECLINE_ADMISSION"
  | "ARCHIVE_ADMISSION"
  | "VIEW_ADMISSION_HISTORY"

  // Enrollment
  | "VIEW_OWN_ENROLLMENT"
  | "VIEW_FAMILY_ENROLLMENT"
  | "SEARCH_ENROLLMENT"
  | "CREATE_ENROLLMENT"
  | "EDIT_ENROLLMENT"
  | "APPROVE_ENROLLMENT"
  | "WITHDRAW_ENROLLMENT"
  | "ARCHIVE_ENROLLMENT"
  | "VIEW_ENROLLMENT_HISTORY"

  // Assignments
  | "VIEW_OWN_ASSIGNMENTS"
  | "VIEW_CHILD_ASSIGNMENTS"
  | "VIEW_CLASSROOM_ASSIGNMENTS"
  | "CREATE_ASSIGNMENT"
  | "EDIT_ASSIGNMENT"
  | "PUBLISH_ASSIGNMENT"
  | "GRADE_ASSIGNMENT"
  | "RETURN_ASSIGNMENT"

  // Administration
  | "VIEW_REPORTS"
  | "MANAGE_USERS"
  | "VIEW_AUDIT_LOG"
  | "MANAGE_SYSTEM";

const permissionMap: Record<
  NorseOneRole,
  readonly NorseOnePermission[]
> = {
  STUDENT: [
    "VIEW_OWN_PROFILE",
    "VIEW_OWN_ATTENDANCE",
    "VIEW_OWN_MESSAGES",
    "VIEW_OWN_ADMISSION",
    "VIEW_OWN_ENROLLMENT",
    "VIEW_OWN_ASSIGNMENTS",
  ],

  PARENT: [
    "VIEW_OWN_PROFILE",
    "VIEW_CHILD_PROFILE",
    "VIEW_CHILD_ATTENDANCE",
    "VIEW_CHILD_MESSAGES",
    "VIEW_FAMILY_ADMISSION",
    "VIEW_FAMILY_ENROLLMENT",
    "VIEW_CHILD_ASSIGNMENTS",
    "SEARCH_ADMISSIONS",
    "SEARCH_ENROLLMENT",
  ],

  TEACHER: [
    "VIEW_OWN_PROFILE",
    "VIEW_STUDENTS",

    "VIEW_CURRICULUM",
    "SEARCH_CURRICULUM",

    "VIEW_CLASSROOM_ATTENDANCE",
    "SEARCH_ATTENDANCE",
    "CREATE_ATTENDANCE",
    "EDIT_ATTENDANCE",
    "CORRECT_ATTENDANCE",
    "VIEW_ATTENDANCE_HISTORY",

    "VIEW_STAFF_MESSAGES",
    "SEARCH_MESSAGES",
    "SEND_MESSAGE",

    "VIEW_CLASSROOM_ASSIGNMENTS",
    "CREATE_ASSIGNMENT",
    "EDIT_ASSIGNMENT",
    "PUBLISH_ASSIGNMENT",
    "GRADE_ASSIGNMENT",
    "RETURN_ASSIGNMENT",

    "VIEW_REPORTS",
  ],

  ASSISTANT: [
    "VIEW_OWN_PROFILE",
    "VIEW_STUDENTS",
    "VIEW_CURRICULUM",
    "SEARCH_CURRICULUM",
    "VIEW_CLASSROOM_ATTENDANCE",
    "SEARCH_ATTENDANCE",
    "CREATE_ATTENDANCE",
    "EDIT_ATTENDANCE",
    "VIEW_CLASSROOM_ASSIGNMENTS",
    "VIEW_STAFF_MESSAGES",
    "SEND_MESSAGE",
  ],

  SUPPORT: [
    "VIEW_OWN_PROFILE",
    "VIEW_STUDENTS",

    "SEARCH_ADMISSIONS",
    "CREATE_ADMISSION",
    "EDIT_ADMISSION",
    "REVIEW_ADMISSION",

    "SEARCH_ENROLLMENT",
    "CREATE_ENROLLMENT",
    "EDIT_ENROLLMENT",

    "SEARCH_MESSAGES",
    "SEND_MESSAGE",

    "VIEW_REPORTS",
  ],

  DIRECTOR: [
    "VIEW_OWN_PROFILE",
    "VIEW_STUDENTS",

    "VIEW_CURRICULUM",
    "SEARCH_CURRICULUM",
    "CREATE_CURRICULUM",
    "EDIT_CURRICULUM",
    "PUBLISH_CURRICULUM",
    "ARCHIVE_CURRICULUM",
    "RESTORE_CURRICULUM",
    "VIEW_CURRICULUM_HISTORY",

    "VIEW_CLASSROOM_ATTENDANCE",
    "SEARCH_ATTENDANCE",
    "CREATE_ATTENDANCE",
    "EDIT_ATTENDANCE",
    "CORRECT_ATTENDANCE",
    "VIEW_ATTENDANCE_HISTORY",

    "SEARCH_MESSAGES",
    "SEND_MESSAGE",
    "EDIT_MESSAGE",
    "ARCHIVE_MESSAGE",
    "VIEW_MESSAGE_HISTORY",

    "SEARCH_ADMISSIONS",
    "CREATE_ADMISSION",
    "EDIT_ADMISSION",
    "REVIEW_ADMISSION",
    "APPROVE_ADMISSION",
    "DECLINE_ADMISSION",
    "ARCHIVE_ADMISSION",
    "VIEW_ADMISSION_HISTORY",

    "SEARCH_ENROLLMENT",
    "CREATE_ENROLLMENT",
    "EDIT_ENROLLMENT",
    "APPROVE_ENROLLMENT",
    "WITHDRAW_ENROLLMENT",
    "ARCHIVE_ENROLLMENT",
    "VIEW_ENROLLMENT_HISTORY",

    "VIEW_REPORTS",
    "MANAGE_USERS",
  ],

  ADMINISTRATOR: [
    "VIEW_OWN_PROFILE",
    "VIEW_STUDENTS",

    "VIEW_CURRICULUM",
    "SEARCH_CURRICULUM",
    "CREATE_CURRICULUM",
    "EDIT_CURRICULUM",
    "PUBLISH_CURRICULUM",
    "ARCHIVE_CURRICULUM",
    "RESTORE_CURRICULUM",
    "VIEW_CURRICULUM_HISTORY",

    "VIEW_CLASSROOM_ATTENDANCE",
    "SEARCH_ATTENDANCE",
    "CREATE_ATTENDANCE",
    "EDIT_ATTENDANCE",
    "CORRECT_ATTENDANCE",
    "VIEW_ATTENDANCE_HISTORY",

    "SEARCH_MESSAGES",
    "SEND_MESSAGE",
    "EDIT_MESSAGE",
    "ARCHIVE_MESSAGE",
    "VIEW_MESSAGE_HISTORY",

    "SEARCH_ADMISSIONS",
    "CREATE_ADMISSION",
    "EDIT_ADMISSION",
    "REVIEW_ADMISSION",
    "APPROVE_ADMISSION",
    "DECLINE_ADMISSION",
    "ARCHIVE_ADMISSION",
    "VIEW_ADMISSION_HISTORY",

    "SEARCH_ENROLLMENT",
    "CREATE_ENROLLMENT",
    "EDIT_ENROLLMENT",
    "APPROVE_ENROLLMENT",
    "WITHDRAW_ENROLLMENT",
    "ARCHIVE_ENROLLMENT",
    "VIEW_ENROLLMENT_HISTORY",

    "VIEW_REPORTS",
    "MANAGE_USERS",
    "VIEW_AUDIT_LOG",
    "MANAGE_SYSTEM",
  ],

  DEVELOPER: [
    "VIEW_OWN_PROFILE",
    "VIEW_AUDIT_LOG",
    "MANAGE_SYSTEM",
  ],
};

export function roleHasPermission(
  role: NorseOneRole,
  permission: NorseOnePermission
): boolean {
  return permissionMap[role].includes(permission);
}

export function getRolePermissions(
  role: NorseOneRole
): readonly NorseOnePermission[] {
  return permissionMap[role];
}